include: package:lints/recommended.yaml

linter:
  rules:
    annotate_overrides: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    annotate_overrides: error
    mixin_inherits_from_not_object: ignore
    deprecated_field: ignore
