name: fpdart
version: 0.6.0-dev.1
homepage: https://www.sandromaglione.com/
repository: https://github.com/SandroMaglione/fpdart
description: Functional programming in Dart and Flutter. All the main functional programming types and patterns fully documented, tested, and with examples.
author: Maglione Sandro <lass.maglio@gmail.com>
documentation: https://www.sandromaglione.com/course/fpdart-functional-programming-dart-and-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  glados: ^1.1.6

screenshots:
  - description: "Basic usage of fpdart Option, Either, TaskEither types."
    path: example/screenshots/screenshot_fpdart.png
