name: fpdart
version: 0.0.13
homepage: https://www.sandromaglione.com/
repository: https://github.com/SandroMaglione/fpdart
description: Functional programming in Dart and Flutter. All the main functional programming types and patterns fully documented, tested, and with examples.
author: Maglione Sandro <lass.maglio@gmail.com>

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.5
