name: fpdart
version: 0.4.0
homepage: https://www.sandromaglione.com/
repository: https://github.com/SandroMaglione/fpdart
description: Functional programming in Dart and Flutter. All the main functional programming types and patterns fully documented, tested, and with examples.
author: Maglione Sandro <lass.maglio@gmail.com>

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  glados: ^1.1.6
