name: fpdart_do_constructor_pitfalls
publish_to: none
version: 0.1.0
homepage: https://www.sandromaglione.com/
repository: https://github.com/SandroMaglione/fpdart
description: Example of Functional programming in Dart and Flutter using fpdart. Pitfalls to avoid when using the do constructor.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fpdart:
    path: ../../packages/fpdart

dev_dependencies:
  lint: ^2.1.2
  test: ^1.24.3
  mocktail: ^0.3.0
